mint by icp
Psychedelic/dank pull request #48
Opened 2022-01-11 22:36 UTC by scott-dn

2022-01-12 06:50 UTC, flyq commented on xtc/src/ledger.rs
> +    let caller_account = AccountIdentifier::new(ic_types::PrincipalId::from(caller), None);
if there is a sub_account, it will be better universality.

2022-01-12 07:12 UTC, flyq commented on xtc/src/ledger.rs
> +            let cycles = compute_fee(0); // TODO: calculate cycles with rate
https://github.com/dfinity/ic/blob/78ded5b98d/rs/nns/cmc/src/main.rs#L501-L505

2022-01-13 05:52 UTC, ccyanxyz approved these changes

2022-01-13 13:37 UTC, scott-dn commented on xtc/Cargo.toml
> +ledger-canister = { git="https://github.com/flyq/ic" }
as discuss, we will keep `flyq` repo for now since `dfinity` have had some internal crates conflicted

2022-01-13 13:42 UTC, scott-dn commented on xtc/src/ledger.rs
> +            "send_dfx",
good point, let's me explore the `send_pb` option

2022-01-13 17:53 UTC, qti3e requested changes
Awesome, the overall flow is perfect, there are only some code quality concerns which i tried to point out. but beside that it's amazing job!

2022-01-13 17:53 UTC, qti3e commented on xtc/src/ledger.rs
> +    ic.get::<UsedBlocks>()
use `ic::`

2022-01-13 17:53 UTC, qti3e commented on xtc/src/ledger.rs
> +    ic.get::<UsedBlocks>().contains(&block_number)
use `ic:get`

2022-01-13 17:53 UTC, qti3e commented on xtc/src/ledger.rs
> +    ic.get::<UsedMapBlocks>().get(&block_number)
use `ic::get`

2022-01-13 17:53 UTC, qti3e commented on xtc/src/ledger.rs
> +    let caller = ic.caller();
again please don't use the `get_context` method

2022-01-13 17:53 UTC, qti3e commented on xtc/src/ledger.rs
> +    };
To be honest I'm scared of this nested match expressions, let's see if we can improve it.

for example you can use `response.map_err(|_| TxError::Other)?` to remove the high level match expression, also on an Option<T> you can use `.ok_or(TxError::Other)?`

2022-01-13 17:53 UTC, qti3e commented on xtc/src/ledger.rs
> +    };
You can remove the match expression by using `let block = encode_block.decode(). map_err(|_| TxError::Other)?`

2022-01-13 17:53 UTC, qti3e commented on xtc/src/upgrade.rs
> +    *(ic.get_mut::<UsedMapBlocks>()) = stable.used_map_blocks;
use `ic::store::<UsedBlocks>(stable.used_blocks); ...`

2022-01-14 13:08 UTC, qti3e approved these changes
LGTM

2022-01-14 21:22 UTC, merged